use base64::{engine::general_purpose::STANDARD, Engine};
use burn::prelude::*;
use burn::backend::Wgpu;
use burn::backend::wgpu::WgpuDevice;
use cubecl_runtime::config::{
    CubeClRuntimeConfig,
    compilation::CompilationConfig,
    cache::CacheConfig,
};
use cubecl_common::config::RuntimeConfig as _;
use std::sync::Once;

static SHADER_CACHE_INIT: Once = Once::new();
use image::imageops::FilterType;

use crate::Keypoint;

// Auto-generated by burn-onnx in build.rs (lands in OUT_DIR/src/model/)
mod rtmpose {
    include!(concat!(env!("OUT_DIR"), "/src/model/rtmpose.rs"));
}

const INPUT_W: u32 = 192;
const INPUT_H: u32 = 256;
const NUM_KPS: usize = 17;
const SIMCC_SPLIT: f32 = 2.0;

const MEAN: [f32; 3] = [123.675, 116.28, 103.53];
const STD:  [f32; 3] = [58.395,  57.12,  57.375];

type B = Wgpu;

pub struct Model {
    inner: rtmpose::Model<B>,
    device: WgpuDevice,
}

impl Model {
    pub fn new() -> Result<Self, String> {
        // Register shader cache before the WGPU device is created.
        // Must run before any cubecl code calls CubeClRuntimeConfig::get().
        SHADER_CACHE_INIT.call_once(|| {
            let cache_dir = dirs::cache_dir()
                .unwrap_or_else(std::env::temp_dir)
                .join("pose_estimation")
                .join("shaders");
            let config = CubeClRuntimeConfig {
                compilation: CompilationConfig {
                    cache: Some(CacheConfig::File(cache_dir)),
                    ..Default::default()
                },
                ..Default::default()
            };
            CubeClRuntimeConfig::set(config);
        });

        let device = WgpuDevice::default();
        let inner = rtmpose::Model::from_embedded(&device);
        Ok(Self { inner, device })
    }
}

pub fn run_pose(
    model: &Model,
    jpeg_b64: &str,
    orig_w: u32,
    orig_h: u32,
) -> Result<Vec<Keypoint>, String> {
    // 1. decode JPEG → resize 192×256 → RGB
    let bytes = STANDARD.decode(jpeg_b64).map_err(|e| e.to_string())?;
    let img = image::load_from_memory(&bytes)
        .map_err(|e| e.to_string())?
        .resize_exact(INPUT_W, INPUT_H, FilterType::Triangle)
        .to_rgb8();

    // 2. build NCHW float tensor, normalised
    let raw = img.into_raw(); // HWC u8
    let (h, w) = (INPUT_H as usize, INPUT_W as usize);
    let mut data = vec![0f32; 3 * h * w];
    for y in 0..h {
        for x in 0..w {
            for c in 0..3 {
                data[c * h * w + y * w + x] =
                    (raw[(y * w + x) * 3 + c] as f32 - MEAN[c]) / STD[c];
            }
        }
    }

    let input = Tensor::<B, 4>::from_data(
        TensorData::new(data, [1, 3, INPUT_H as usize, INPUT_W as usize]),
        &model.device,
    );

    // 3. forward → SimCC logits: simcc_x [1,17,384], simcc_y [1,17,512]
    let (simcc_x, simcc_y) = model.inner.forward(input);

    // 4. copy to CPU and argmax-decode keypoints
    let x_flat: Vec<f32> = simcc_x.into_data().to_vec().map_err(|e| format!("{e:?}"))?;
    let y_flat: Vec<f32> = simcc_y.into_data().to_vec().map_err(|e| format!("{e:?}"))?;

    let sim_w = (INPUT_W as f32 * SIMCC_SPLIT) as usize;
    let sim_h = (INPUT_H as f32 * SIMCC_SPLIT) as usize;

    eprintln!("[pose] x_flat len={} sim_w={} | y_flat len={} sim_h={}",
        x_flat.len(), sim_w, y_flat.len(), sim_h);
    eprintln!("[pose] x range=[{:.3}, {:.3}]  y range=[{:.3}, {:.3}]",
        x_flat.iter().cloned().fold(f32::INFINITY, f32::min),
        x_flat.iter().cloned().fold(f32::NEG_INFINITY, f32::max),
        y_flat.iter().cloned().fold(f32::INFINITY, f32::min),
        y_flat.iter().cloned().fold(f32::NEG_INFINITY, f32::max));

    let mut kps = Vec::with_capacity(NUM_KPS);
    for k in 0..NUM_KPS {
        let xs = &x_flat[k * sim_w..(k + 1) * sim_w];
        let ys = &y_flat[k * sim_h..(k + 1) * sim_h];

        let (xi, xv) = argmax(xs);
        let (yi, yv) = argmax(ys);

        let px = (xi as f32 / SIMCC_SPLIT) * orig_w as f32 / INPUT_W as f32;
        let py = (yi as f32 / SIMCC_SPLIT) * orig_h as f32 / INPUT_H as f32;
        let score = (xv + yv) / 2.0;

        eprintln!("[pose] kp[{k:02}] xi={xi} xv={xv:.3} yi={yi} yv={yv:.3} → px={px:.1} py={py:.1} score={score:.3}");

        kps.push(Keypoint { x: px, y: py, score });
    }

    Ok(kps)
}

fn argmax(slice: &[f32]) -> (usize, f32) {
    slice
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.partial_cmp(b.1).unwrap_or(std::cmp::Ordering::Less))
        .map(|(i, &v)| (i, v))
        .unwrap_or((0, 0.0))
}
